Upgrade to netcoreapp3.1 and standardize logging
ucdavis/Anlab pull request #863
Opened 2021-02-05 00:37 UTC by sprucely

There was a drawn-out game of musical chairs in getting npm packages configured and playing nicely. Well mostly nicely, as it appears hmr is not working. If anything looks like an odd choice, I can revisit it.

2021-02-05 17:44 UTC, sprucely commented
Started working on azure pipeline and then realized I hadn't run the karma tests. Gotta get those passing again...

2021-02-05 21:03 UTC, srkirkland approved these changes

2021-02-05 21:04 UTC, srkirkland commented
I think it all looked good from a code perspective.  Once the JS tests are updated we'll need to do our own testing before we deploy but everything looked like a good approach to me.

2021-02-08 21:35 UTC, jSylvestre requested changes
Failing locally after CAS login.
Needs to be tested once this is fixed

2021-02-10 00:47 UTC, sprucely commented on Anlab.Mvc/Client/components/Summary.tsx
> +                <Button className="btn btn-order" disabled={!this.props.canSubmit || this.props.isSubmitting} onClick={() => this.props.onSubmit()}>
Just saw this question. Right, it was just to satisfy typescript.

2021-02-25 18:12 UTC, closed without merging