CRA upgrade
ucdavis/Anlab pull request #929
Opened 2022-04-21 18:00 UTC by srkirkland

Upgrade to CRA, which is really just the order page.   Created a few orders and everything appears to be working.  We do get console warnings in dev, the most concerning of which are about deprecated/removed react lifecycle events used by the bootstrap and datepicker libs, though these components still seem to be working fine so perhaps it doesn't affect us.

Tests are completely broken (karma/enzyme doesn't support react17) so submitting as a draft while I fix or consider different options.

2022-04-22 15:02 UTC, jSylvestre requested changes

2022-04-22 15:02 UTC, jSylvestre commented on Anlab.Mvc/Views/Order/Edit.cshtml
> -        App.orderId = @Model.Order.Id;
I think this is causing a new order to be created on edit

2022-04-22 16:30 UTC, jSylvestre approved these changes

2022-04-22 17:25 UTC, jSylvestre commented on Anlab.Mvc/ClientApp/src/components/ClientId.tsx
> +    private _notEmpty = (value: string) => {
Nice

2022-04-25 17:41 UTC, sprucely approved these changes
Looked at it last week, so just went over the most recent commits. Looks good.

2022-04-25 17:42 UTC, merged